import {
  Navigation,
  MapPin,
  Filter,
  Layers,
  Plus,
  Activity,
  BarChart3,
  Wallet,
  Briefcase,
  User,
  Menu,
  X,
  CheckCircle2,
  AlertTriangle,
  Clock,
  Search,
  ChevronRight,
  LayoutDashboard,
  Database,
  ChevronLeft,
  ArrowRight,
  ShieldCheck,
  Zap,
  TrendingUp,
  Users,
  Euro,
  FileJson,
  FileSpreadsheet,
  Download,
  Camera
} from "lucide-react";

export const Icons = {
  map: Navigation,
  pin: MapPin,
  filter: Filter,
  layers: Layers,
  add: Plus,
  activity: Activity,
  dashboard: BarChart3,
  budget: Wallet,
  worker: Briefcase,
  user: User,
  menu: Menu,
  close: X,
  resolved: CheckCircle2,
  urgent: AlertTriangle,
  pending: Clock,
  search: Search,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  layout: LayoutDashboard,
  database: Database,
  arrowRight: ArrowRight,
  transparency: ShieldCheck,
  ai: Zap,
  zap: Zap,
  shieldCheck: ShieldCheck,
  trendingUp: TrendingUp,
  users: Users,
  euro: Euro,
  fileJson: FileJson,
  fileSpreadsheet: FileSpreadsheet,
  download: Download,
  camera: Camera,
  clock: Clock
};
